seed: 42
model_name: "LeNet"
epochs: 50
batch_size: 128
num_classes: 10
loss_function: "CrossEntropyLoss"
optimizer: "Adam"
learning_rate: 0.001
lr_scheduler: "StepLR"
lr_scheduler_args:
  step_size: 10
  gamma: 0.1
train_args:
  shuffle: True
  num_workers: 2
  prefetch_factor: 1
test_args:
  shuffle: True
  num_workers: 2
  prefetch_factor: 1
metrics:
  - "accuracy"
logger: "neptune"
